import type { SourceDef } from "./types";

/**
 * 1단계 소스 레지스트리 — RSS/공개 API만으로 수집 가능한 것.
 * 스크레이핑이 필요한 소스(배타적사용권 게시판, 보험연구원 등)는 2단계에서 추가.
 *
 * 주의: 피드 URL 상당수는 조사 시점에 실환경 검증을 못 했다(개발망 이그레스 차단).
 * 수집 실패는 소스별 status로 드러나므로 배포 후 상태 스트립에서 확인할 것.
 */
export const SOURCES: SourceDef[] = [
  // ── 국내 뉴스 ───────────────────────────────────────────────
  {
    id: "naver-insurance",
    name: "네이버 뉴스 검색",
    category: "kr-news",
    kind: "naver-news",
    lang: "ko",
    query: "보험",
    homepage: "https://news.naver.com",
    limit: 30,
  },
  {
    id: "insnews",
    name: "한국보험신문",
    category: "kr-news",
    kind: "rss",
    lang: "ko",
    url: "https://www.insnews.co.kr/rss/allArticle.xml",
    homepage: "https://www.insnews.co.kr",
  },
  {
    id: "insweek",
    name: "보험신보",
    category: "kr-news",
    kind: "rss",
    lang: "ko",
    url: "https://www.insweek.co.kr/rss/allArticle.xml",
    homepage: "https://www.insweek.co.kr",
  },
  {
    id: "fins",
    name: "보험매일",
    category: "kr-news",
    kind: "rss",
    lang: "ko",
    url: "https://www.fins.co.kr/rss/allArticle.xml",
    homepage: "https://www.fins.co.kr",
  },

  // ── 해외 뉴스 ───────────────────────────────────────────────
  {
    id: "insurance-journal",
    name: "Insurance Journal",
    category: "global-news",
    kind: "rss",
    lang: "en",
    url: "https://www.insurancejournal.com/feed/",
    homepage: "https://www.insurancejournal.com",
  },
  {
    id: "reinsurance-news",
    name: "Reinsurance News",
    category: "global-news",
    kind: "rss",
    lang: "en",
    url: "https://www.reinsurancene.ws/feed/",
    homepage: "https://www.reinsurancene.ws",
  },
  {
    id: "artemis",
    name: "Artemis (ILS·캣본드)",
    category: "global-news",
    kind: "rss",
    lang: "en",
    url: "https://www.artemis.bm/news/feed/",
    homepage: "https://www.artemis.bm",
  },
  {
    id: "coverager",
    name: "Coverager",
    category: "global-news",
    kind: "rss",
    lang: "en",
    url: "https://coverager.com/feed/",
    homepage: "https://coverager.com",
  },
  {
    id: "ib-us",
    name: "Insurance Business (US)",
    category: "global-news",
    kind: "rss",
    lang: "en",
    url: "https://www.insurancebusinessmag.com/us/rss/",
    homepage: "https://www.insurancebusinessmag.com/us/",
  },
  {
    id: "life-insurance-intl",
    name: "Life Insurance International",
    category: "global-news",
    kind: "rss",
    lang: "en",
    url: "https://www.lifeinsuranceinternational.com/feed/",
    homepage: "https://www.lifeinsuranceinternational.com",
  },

  // ── 정책·공시 ───────────────────────────────────────────────
  {
    id: "korea-kr-fsc",
    name: "금융위원회 (정책브리핑)",
    category: "policy",
    kind: "rss",
    lang: "ko",
    url: "https://www.korea.kr/rss/dept_fsc.xml",
    homepage: "https://www.fsc.go.kr",
    // 금융위 전체 보도자료 중 보험 관련만
    include: ["보험", "실손", "연금", "IFRS", "지급여력", "K-ICS"],
    limit: 30,
  },
  {
    id: "dart-insurers",
    name: "DART 보험사 공시",
    category: "policy",
    kind: "dart",
    lang: "ko",
    homepage: "https://dart.fss.or.kr",
    limit: 30,
  },
  // ── 규제 레이더 (선행 신호 + 약관 리스크) ──
  {
    id: "fss-dispute",
    name: "금감원 분쟁조정례",
    category: "policy",
    kind: "scrape",
    lang: "ko",
    homepage: "https://www.fss.or.kr",
    limit: 10,
  },
  {
    id: "fsc-rule-notice",
    name: "금융위 규정변경예고",
    category: "policy",
    kind: "scrape",
    lang: "ko",
    homepage: "https://www.fsc.go.kr/po1002",
    // 스크랩 아이템은 summary가 없어 제목만 매칭됨 — 보험 관련만 통과
    include: ["보험", "실손", "지급여력", "K-ICS"],
    limit: 10,
  },
  {
    id: "assembly-bills",
    name: "국회 의안 — 보험",
    category: "policy",
    kind: "assembly",
    lang: "ko",
    homepage: "https://likms.assembly.go.kr",
    limit: 15,
  },

  // ── 신상품 ─────────────────────────────────────────────────
  {
    id: "klia-exclusive",
    name: "생보협회 배타적사용권",
    category: "new-products",
    kind: "scrape",
    lang: "ko",
    market: "KR",
    homepage: "https://www.klia.or.kr/member/exclUse/exclResult/list.do",
    limit: 10,
  },
  {
    id: "knia-exclusive",
    name: "손보협회 배타적사용권",
    category: "new-products",
    kind: "scrape",
    lang: "ko",
    market: "KR",
    homepage: "https://www.knia.or.kr/report/new-review/new-review02",
    limit: 10,
  },
  {
    id: "coverager-product",
    name: "Coverager — Product",
    category: "new-products",
    kind: "rss",
    lang: "en",
    market: "GLOBAL",
    url: "https://coverager.com/category/product/feed/",
    homepage: "https://coverager.com/category/product/",
  },
  {
    id: "naver-new-products",
    name: "네이버 뉴스 — 신상품",
    category: "new-products",
    kind: "naver-news",
    lang: "ko",
    market: "KR",
    query: "보험 신상품 출시",
    homepage: "https://news.naver.com",
  },
  {
    id: "naver-exclusive-right",
    name: "네이버 뉴스 — 배타적사용권",
    category: "new-products",
    kind: "naver-news",
    lang: "ko",
    market: "KR",
    query: "배타적사용권",
    homepage: "https://news.naver.com",
  },
  // Google News RSS 검색 — 무인증 표준 RSS. 요약이 제목 중복이라 noSummary.
  {
    id: "gnews-jp-products",
    name: "Google News (日本) — 保険 新商品",
    category: "new-products",
    kind: "rss",
    lang: "ja",
    market: "JP",
    url: `https://news.google.com/rss/search?q=${encodeURIComponent("保険 新商品 発売")}&hl=ja&gl=JP&ceid=JP:ja`,
    homepage: "https://news.google.com",
    noSummary: true,
    limit: 15,
  },
  {
    id: "gnews-cn-products",
    name: "Google News (中国) — 保险 新产品",
    category: "new-products",
    kind: "rss",
    lang: "zh",
    market: "CN",
    // 중국 본토 매체 커버리지는 제한적일 수 있음 (홍콩·대만·해외 중화권 매체 포함)
    url: `https://news.google.com/rss/search?q=${encodeURIComponent("保险 新产品 发布")}&hl=zh-CN&gl=CN&ceid=CN:zh-Hans`,
    homepage: "https://news.google.com",
    noSummary: true,
    limit: 15,
  },

  // ── 리서치 ─────────────────────────────────────────────────
  {
    id: "kiri-reports",
    name: "보험연구원 리포트",
    category: "research",
    kind: "scrape",
    lang: "ko",
    homepage: "https://www.kiri.or.kr",
    limit: 10,
  },
  // 컨설팅펌 보험 인사이트 — 직접 스크레이핑 실패 시 Jina Reader 폴백
  {
    id: "bcg-insurance",
    name: "BCG — Insurance",
    category: "research",
    kind: "scrape",
    lang: "en",
    homepage: "https://www.bcg.com/industries/insurance/overview",
    limit: 8,
  },
  {
    id: "bain-insurance",
    name: "Bain — Insurance",
    category: "research",
    kind: "scrape",
    lang: "en",
    homepage: "https://www.bain.com/insights/industry-insights/insurance-insights/",
    limit: 8,
  },
  {
    id: "deloitte-insurance",
    name: "Deloitte — Insurance",
    category: "research",
    kind: "scrape",
    lang: "en",
    homepage: "https://www.deloitte.com/us/en/insights/industry/insurance.html",
    limit: 8,
  },
  {
    id: "mckinsey",
    name: "McKinsey Insights",
    category: "research",
    kind: "rss",
    lang: "en",
    url: "https://www.mckinsey.com/insights/rss",
    homepage:
      "https://www.mckinsey.com/industries/financial-services/our-insights/insurance",
    // 전사 피드 → 보험 관련 항목만
    include: ["insurance", "insurer", "insurtech", "reinsurance", "actuar"],
    limit: 15,
  },
  {
    id: "naver-kiri",
    name: "네이버 뉴스 — 보험연구원",
    category: "research",
    kind: "naver-news",
    lang: "ko",
    query: "보험연구원",
    homepage: "https://www.kiri.or.kr",
  },

  // ── 위험률·의료 (인보험 위험률 개발 원천) ──────────────────
  // 국내 학술 논문 — KCI 제목 키워드 검색 (보험학회지·계리학연구·리스크관리연구 등)
  {
    id: "kci-riskrate",
    name: "KCI 논문 — 위험률",
    category: "risk-research",
    kind: "kci",
    lang: "ko",
    query: "위험률",
    homepage: "https://www.kci.go.kr",
    limit: 10,
  },
  {
    id: "kci-mortality",
    name: "KCI 논문 — 사망률",
    category: "risk-research",
    kind: "kci",
    lang: "ko",
    query: "사망률",
    homepage: "https://www.kci.go.kr",
    limit: 10,
  },
  {
    id: "kci-incidence",
    name: "KCI 논문 — 발생률",
    category: "risk-research",
    kind: "kci",
    lang: "ko",
    query: "발생률",
    homepage: "https://www.kci.go.kr",
    limit: 10,
  },
  // 해외 의학 논문 — 한국 대상 발생률·사망률·유병률 (키 불필요)
  {
    id: "pubmed-kr",
    name: "PubMed — 한국 역학",
    category: "risk-research",
    kind: "pubmed",
    lang: "en",
    query:
      "(incidence[Title] OR mortality[Title] OR prevalence[Title]) AND (Korea[Title/Abstract] OR Korean[Title/Abstract])",
    homepage: "https://pubmed.ncbi.nlm.nih.gov",
    limit: 12,
  },
  // 통계 공표 감지 — 정책브리핑 부처별 RSS + 키워드 필터
  // (부처 코드는 korea.kr/etc/rss.do에서 확인 필요 — 미검증)
  {
    id: "kostat-releases",
    name: "통계청 공표",
    category: "risk-research",
    kind: "rss",
    lang: "ko",
    url: "https://www.korea.kr/rss/dept_kostat.xml",
    homepage: "https://kostat.go.kr",
    include: ["사망원인", "생명표", "기대수명", "사망률", "암등록", "고령자", "장래인구"],
    limit: 10,
  },
  {
    id: "kdca-releases",
    name: "질병관리청 공표",
    category: "risk-research",
    kind: "rss",
    lang: "ko",
    url: "https://www.korea.kr/rss/dept_kdca.xml",
    homepage: "https://www.kdca.go.kr",
    include: ["발생률", "유병률", "건강영양", "만성질환", "감염병", "사망"],
    limit: 10,
  },
  // 의료비 영향 이벤트 — 급여화·수가·약가 결정과 신의료기술
  {
    id: "mohw-releases",
    name: "보건복지부 — 급여·수가",
    category: "risk-research",
    kind: "rss",
    lang: "ko",
    url: "https://www.korea.kr/rss/dept_mohw.xml",
    homepage: "https://www.mohw.go.kr",
    include: ["급여", "비급여", "수가", "약가", "건강보험", "신의료기술", "본인부담"],
    limit: 10,
  },
  {
    id: "naver-medtech",
    name: "네이버 뉴스 — 신의료기술",
    category: "risk-research",
    kind: "naver-news",
    lang: "ko",
    query: "신의료기술",
    homepage: "https://news.naver.com",
    limit: 10,
  },
  {
    id: "naver-hipc",
    name: "네이버 뉴스 — 건정심",
    category: "risk-research",
    kind: "naver-news",
    lang: "ko",
    // 건강보험정책심의위원회 — 급여화·수가 결정의 공식 이벤트 스트림
    query: "건강보험정책심의위원회",
    homepage: "https://news.naver.com",
    limit: 10,
  },
  {
    id: "naver-nonpayment",
    name: "네이버 뉴스 — 비급여·실손",
    category: "risk-research",
    kind: "naver-news",
    lang: "ko",
    query: "비급여 실손",
    homepage: "https://news.naver.com",
    limit: 10,
  },
  // 글로벌 (한국 한정 아님 — 전부 키 불필요)
  {
    id: "pubmed-global",
    name: "PubMed — 글로벌 역학·통계",
    category: "risk-research",
    kind: "pubmed",
    lang: "en",
    // GBD·연례 암통계·기대수명 논문 — 계리 가정의 글로벌 벤치마크
    query:
      '"global burden"[Title] OR "cancer statistics"[Title] OR "life expectancy"[Title]',
    homepage: "https://pubmed.ncbi.nlm.nih.gov",
    limit: 12,
  },
  {
    id: "who-news",
    name: "WHO 발표",
    category: "risk-research",
    kind: "rss",
    lang: "en",
    url: "https://www.who.int/rss-feeds/news-english.xml",
    homepage: "https://www.who.int",
    include: [
      "statistic",
      "mortality",
      "life expectancy",
      "cancer",
      "diabetes",
      "burden",
      "disease",
    ],
    limit: 10,
  },
  {
    id: "arxiv-actuarial",
    name: "arXiv — 사망률 모형·장수리스크",
    category: "risk-research",
    kind: "rss",
    lang: "en",
    // arXiv API는 Atom 피드를 반환 → 기존 RSS 파서로 처리
    url:
      "https://export.arxiv.org/api/query?search_query=" +
      encodeURIComponent(
        'abs:"mortality model" OR abs:"longevity risk" OR abs:"mortality improvement"',
      ) +
      "&sortBy=submittedDate&sortOrder=descending&max_results=10",
    homepage: "https://arxiv.org",
    limit: 10,
  },
  {
    id: "gnews-global-stats",
    name: "Google News — 글로벌 보건통계",
    category: "risk-research",
    kind: "rss",
    lang: "en",
    url: `https://news.google.com/rss/search?q=${encodeURIComponent('"life expectancy" OR "mortality rate" OR "cancer statistics"')}&hl=en-US&gl=US&ceid=US:en`,
    homepage: "https://news.google.com",
    noSummary: true,
    limit: 10,
  },
];

export function sourcesByCategory(category: string): SourceDef[] {
  return SOURCES.filter((s) => s.category === category);
}
